### PR TITLE
New app icon

### PR DESCRIPTION
**Pull request by Donnnno**
preview image:

ic_launcher_round

Also small copyright notice, no worries you're free to use it in any way you like :^) 

Copyright 2021 Onno van den Dungen (@Donnnno) 
under [CC-BY-SA 3.0 Unported](http://creativecommons.org/licenses/by-sa/3.0/) and [GPLv3](http://www.gnu.org/licenses/gpl-3.0.html)  or later versions of that license.

#16

### CODE REVIEW

**Comment by dkter** [comment]
I love this, thank you so much!

To be clear regarding licensing -- aaaaa is MPL2, just clarifying that it's ok to use the icon in MPL2 software as long as the icon/any derivatives are still under CC BY-SA/GPLv3?

**Comment by Donnnno** [comment]
Oh yea, you can use MLP2 instead of GPLv3 but just use CC BY-SA with it ;)

**Comment by Donnnno** [comment]
btw, I was inspired by this post to make the icon haha: 
https://forum.f-droid.org/t/why-f-droid-spends-resources-to-build-this-app/14765

**Comment by dkter** [comment]
Ha, wasn't aware of that post. Thanks again. I'll probably change the app header colour to match the app icon better and then push an update

**Comment by Donnnno** [comment]
Haha cool, no problemo <3

**Pull request merged**
